media: media
content:
  - name: projects
    label: Projects
    type: collection
    path: '_projects'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: title
        label: Title
        type: string
      - name: thumbnail
        label: Featured Image
        type: image
      - name: media
        label: Image Gallery
        type: image-with-caption
        options:
          multiple: true


          