media: media
content:
  - name: pics
    label: Pics
    type: collection
    path: '_pics'
    view:
      fields: [ image, caption ]
    fields:
      - name: image
        label: image
        type: image
      - name: caption
        label: caption
        type: rich-text  
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: thumbnail
        label: Featured Image
        type: image
      - name: gallery
        label: Image Gallery
        type: image
        options:
          multiple: true
      - name: media
        label: media_items
        type: object
        list: true
        fields:
          - name: image
            label: Image
            type: image
          - name: alt
            label: Alt
            type: rich-text
            options:
              media: false
      - name: slides
        label: slides
        type: reference
        list: true
        options:
          collection: pics
          search: "caption"
          value: "{caption}"
          label: "{caption}"
          image: "{image}"
      - name: blocks
        label: Page Sections
        type: block
        list: true 
        blockKey: type 
        blocks:
          - name: image
            label: Image
            fields:
              - name: image
                label: image
                type: image
              - name: caption
                label: caption
                type: text

  